version: "3"
services:
  web:
    container_name: ${APP_NAME}web
    build:
      context: ./
      dockerfile: videoconverter.Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ".env"
    volumes:
      - "./data:/data"
    hostname: videoconverter.localhost.com